trigger:
  - main  

pool:
  vmImage: 'ubuntu-latest'  

steps:
  - task: aws-cli@1
    displayName: 'Configure AWS CLI'
    inputs:
      awsCredentials: 'aws'
      regionName: 'us-east-1'

  - script: |
      aws s3 mb s3://my-ado-test-bucket
      aws s3 ls
    displayName: 'Create and List S3 Bucket'
